# Generated by Django 3.2 on 2021-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210506_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(to='companies.Category'),
        ),
    ]
